name: Fintechhub avtomatization deployment CI/CD # ziyodev

on:
  push:
    branches:
      - master
      
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: server connaction
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.SERVER_HOST }} 
        username: ${{ secrets.SERVER_USERNAME }} 
        password: ${{ secrets.SERVER_PASSWORD }}
        script: | 
          echo "connected server successfully" 
          cd /home
          
          echo "Deployment successfully."
